# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/app-deployment.yaml
  - base/app-ingress.yaml
  - security/waf-policy.yaml
  - security/k8s-waf-policy.yaml
  


