apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy-map
  namespace: default
spec:
  waf:
    enable: true
    apPolicy: "default/dataguard-policy"
    securityLogs:
      - apLogConf: "default/waf-logconf"
        logDest: "syslog:server=syslog-svc.default.svc.cluster.local:514"
