apiVersion: appprotect.f5.com/v1
kind: APPolicy
metadata:
  name: dataguard-policy
  namespace: security
spec:
  policy:
    name: dataguard-policy
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    enforcementMode: blocking
    blocking-settings:
      violations:
        - name: VIOL_SQL_INJECTION
          alarm: true
          block: true
        - name: VIOL_ATTACK_SIGNATURE
          alarm: true
          block: true
        - name: VIOL_DATA_GUARD
          alarm: true
          block: true
    data-guard:
      enabled: true
      maskData: true
      creditCardNumbers: true
      usSocialSecurityNumbers: true
---
apiVersion: appprotect.f5.com/v1
kind: APLogConf
metadata:
  name: waf-logconf
  namespace: default
spec:
  content:
    format: default
    max_message_size: 64k
  filter:
    request_type: all
