
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp-vs
  namespace: default
spec:
  host: webapp.demo.local
  policies:
    - name: waf-policy-map
  upstreams:
    - name: webapp
      service: webapp-svc
      port: 80
  routes:
    - path: /
      action:
        pass: webapp
