apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: default
  annotations:
    k8s.nginx.org/policies: "default/waf-policy-map"
spec:
  ingressClassName: nginx
  rules:
  - host: webapp.demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-svc
            port:
              number: 80
